import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "index",
    "quickstart",
    "cli-reference",
    "trading-workflows",
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "generated-index",
        title: "API Reference",
        description: "Autogenerated from Kalshi OpenAPI.",
      },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
